import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { MantineProvider, MantineThemeOverride } from '@mantine/core';


export const metadata: Metadata = {
  title: "Product Management Dashboard",
  description: "Generated by Akbar",
};

const theme: MantineThemeOverride = {
  breakpoints: {
    xs: '30em',
    sm: '48em',
    md: '64em',
    lg: '74em',
    xl: '90em',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
// Removed the incorrect function definition

