name: Build and deploy Next.js app to Azure Web App - product-management

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Clear dependencies cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js application
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p release
          cp -r .next release/.next
          cp -r public release/public
          cp package.json release/
          cp next.config.mjs release/
          cp server.js release/ 
          cd release && zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72AC95D8BF2C43F5AFC0AC817CE1B2FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8E77B60B18944754926CFF3246E612E2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9B946F29E294E1CB0DF87AA7A7FB418 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-management'
          package: .